name: Build APK with Buildozer and Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull Buildozer Docker Image
        run: docker pull kivy/buildozer:latest

      - name: Run Buildozer Build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
            kivy/buildozer \
            android debug
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourAppName-APK
          path: |
            .buildozer/android/platform/build-arm64-v8a/dists/yourappname/bin/*.apk
            .buildozer/android/platform/build-armeabi-v7a/dists/yourappname/bin/*.apk
